version: 2
updates:
  # Monitor Swift Package Manager dependencies
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@me"
    assignees:
      - "@me"

  # Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@me"
    assignees:
      - "@me"
